### ISSUE TITLE
Fixed Size

### ISSUE THREAD

**Issue by heinhtetzawycc** [Abhilash-Chandran/number_inc_dec#1]
Should be able to pass size as argument to this widget.Thanks.

**Comment by Abhilash-Chandran** [comment]
Sorry I didn't understand the issue. Which size would you like as parameter..? Could you elaborate a little more. I would be glad to add it. 😄

**Comment by heinhtetzawycc** [comment]
Sorry for my incomplete information.The default size of your widget is a bit large. So It take a lot space in screen and can't use in small container. If you let us to pass the desire size as argument, it will help a lot.Thanks.

**Comment by Abhilash-Chandran** [comment]
I you could some share a piece of code with the issue, I can check it easily. Otherwise it will be difficult to assume all the use case. One thing I can see is I am using the default TextFormField widget which comes with its own sizing constraints from the material spec. Maybe this is interfering with small containers. Meanwhile I will test it in small containers and share the information if I find some issues. Thanks a lot for filing an issue. Hope I can help you soon.

**Comment by heinhtetzawycc** [comment]
What I mean is the size of your container and icon to dynamic something like that 
 width: widget.size,
 height: widget.size * 0.65

**Comment by Abhilash-Chandran** [comment]
As per my understanding this widget doesn't have any fixed size as it uses `Container`, `Column` and `Row` widgets internally which inflates to the given size. But since I use TextFormField we cannot change the height without managing it in the InputDecoration which I already exposed in the attribute `numberFieldDecoration`.

Instead of that, a scaled sizing can be simply achieved with a `Transform` widget. I will expose the scales for the whole widget as well as some attributes for the icons like size and color etc. I hope that this should help you manipulating the size comfortably for the whole widget. Please check the following examples. Hope this will help you out. 😃 

For Example:

**For Scaling**
```dart
// Scale Height alone
NumberInputWithIncrementDecrement(
      controller: TextEditingController(),
      scaleHeight: 0.5,                                   
),
```

```dart
// Scale width alone
NumberInputWithIncrementDecrement(
      controller: TextEditingController(),
      scaleWidth: 0.5,                                   
),
```
```dart
// Scale Height and width.
NumberInputWithIncrementDecrement(
      controller: TextEditingController(),
      scaleHeight: 0.5, 
      scaleWidth: 0.5,                                   
),
```

**For icons** 

```dart
NumberInputWithIncrementDecrement(
    controller: TextEditingController(),
    incIconSize: 32,
    decIconSize: 32,
    incIcon: Icons.plus_one,
    decIcon: Icons.exposure_neg_1,
),
```
Also I change the documentation accordingly.

**Comment by heinhtetzawycc** [comment]
Thanks.It solved my issue.
